###服务启动端口号
server:
  port: 80
###服务名称(服务注册到eureka名称)  
spring:
  application:
    name: app-xhh-zuul
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000
### 配置网关反向代理    
zuul:
  routes:
    api-a:
      ### 以 /api-registered/访问转发到
      path: /api-registered/**
      serviceId: app-tw-registered
    api-b:
      ### 以 /api-parade/访问转发到
      path: /api-parade/**
      serviceId: app-tw-parade
    api-c:
      ### 以 /api-web/访问转发到web接口
      path: /api-web/**
      serviceId: app-tw-web
